name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Add remote host to known_hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files via SCP
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: sshpass -e scp -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/Cristian-web

    - name: Execute commands on VPS
      env:
        SSHPASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -e ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        pm2 stop Cristian-web || true
        cd /root/Cristian-web
        git pull origin main
        npm install
        pm2 start Cristian-web
        EOF
